### ISSUE TITLE
remove custom search from mobile entirely?

### ISSUE THREAD

**Issue by jgravois** [Esri/esri.github.io#104]
in #102 we accidentally introduced a new 'feature'. in mobile emulators (and on real devices) the search box is now hidden entirely (offending [line](https://github.com/Esri/esri.github.io/blob/d0951943e38b9050fe4f632b58517e9259bc27aa/src/assets/js/github.js#L88)).

![screenshot 2017-04-21 12 46 00](https://cloud.githubusercontent.com/assets/3011734/25293622/89059b04-2690-11e7-890e-61c588531878.png)

https://github.com/Esri isn't even displaying our search results, so i vote we just center the button that remains and call it a day.

**Comment by alaframboise** [comment]
@jgravois not sure if this was the new chosen.css or my stuff. Looking at it now. Should be simple.

**Comment by alaframboise** [comment]
Hey @jgravois I rolled everything back to the commit before my CSS edits https://github.com/Esri/esri.github.io/commit/13a48b011df0152651375e705ab566bd959b567f and this is how it was always rendering on iOS devices, which is in alignment with what the chosen doc says about not supporting iOS devices, so I'm not sure it was ever working.

New PR to hide the chosen search coming soon.

![image](https://cloud.githubusercontent.com/assets/2539681/25307309/25a1690e-275c-11e7-8ad4-c8a3f062019d.png)

**Comment by alaframboise** [comment]
Ok this should handle it all.

https://github.com/Esri/esri.github.io/pull/105
