### ISSUE TITLE
Broken License Link in README

### ISSUE THREAD

**Issue by gvmmybear** [Esri/esri.github.io#155]
Hello, I noticed there is a broken link at the bottom of the README file: https://github.com/Esri/esri.github.io/blob/main/README.md 
It redirects to this page: https://raw.githubusercontent.com/Esri/esri.github.com/master/license.txt

**Comment by jgravois** [comment]
feel free to open a PR that changes 'license.txt' to 'LICENSE'

https://raw.githubusercontent.com/Esri/esri.github.com/master/LICENSE
