### ISSUE TITLE
Need search categories

### ISSUE THREAD

**Issue by alaframboise** [Esri/esri.github.io#73]
**Topics - Language**

javascript
nodejs
css
sass
scss
html
ios
osx
swift
objective-c
android
flex
java
python
rest
qt
qml
vb
c#
.net
c
c++
actionscript
typescript
R
xamarin
xml
ruby
php

**Topics - High-Level Categories**

web-development
spatial-analysis
data-management
publishing-sharing

**Topics - Sub-categories (company, technology, industry, event...)**

api
arcgis ?
esri ?
desktop
web
runtime
native
server
app-template
storymaps
government
military
utilities
electric
water
emergency-management
enterprise
maps
webmap
webscene
basemap
cartography
graphics
geometry
symbols
database
dataset
layer
geocoding
geoprocessing
editing
demographics
directions
logistics
projections
statistics
analysis
networking
services
geoservices
intelligence
big-data
dashboard
tools
real-time? (another john suggestion)

**Topics - Misc**

devsummit
uc
sdk?
framework?
sample?
calcite?
bootstrap?

**Comment by jgravois** [comment]
i like these.  i'd just add `native`

i think `arcgis` and `esri` make sense as optional tags too.  they aren't crucial for us to hydrate search in https://esri.github.io, but i like the idea of folks being able to search on them in github itself.

**Comment by alaframboise** [comment]
added `native`

**Comment by alaframboise** [comment]
![image](https://cloud.githubusercontent.com/assets/2539681/24776050/880f3d96-1adc-11e7-9c64-7a12d2967f05.png)
@jgravois @jf990
