### ISSUE TITLE
Banner image broken?

### ISSUE THREAD

**Issue by nixta** [Esri/esri.github.io#75]
Looks like someone chopped the middle out of the banner image. Couple of weird artifacts...

![2017-04-07_11-42-28](https://cloud.githubusercontent.com/assets/25374/24807762/89004690-1b87-11e7-909c-b5b59ac896ff.png)

**Comment by jgravois** [comment]
we pulled it from [here](http://www.esri.com/software/open/open-source).  

looks like they might have intentionally mucked with the contrast because of the overlay text.

**Comment by nixta** [comment]
Looks like they sliced a chunk out of it from the middle and left a line on the right. In fact, yeah, look at the other tabs and the mountain hasn't been Jenga'd: e.g. http://www.esri.com/software/open

Easy then. Just re-pull it from another tab.

**Comment by nixta** [comment]
Attached is a banner image (assuming GH doesn't resize it) that doesn't have the top of the mountain sliced-n-diced.

![banner-esri-github-io](https://cloud.githubusercontent.com/assets/25374/24976350/1810be38-1f97-11e7-9e98-195c121239b9.jpg)
