### ISSUE TITLE
"Topics" header missing

### ISSUE THREAD

**Issue by alaframboise** [Esri/esri.github.io#79]
![image](https://cloud.githubusercontent.com/assets/2539681/24926043/80b50aec-1eb7-11e7-8eed-02001172e50c.png)

**Comment by jgravois** [comment]
i removed the topics header intentionally when we re-engineered search down to one `<optgroup>` because it felt redundant.

if you want to readd it yourself, i won't complain.

**Comment by alaframboise** [comment]
no worries i'm fixing everything now

**Comment by alaframboise** [comment]
Fixed #81
