### ISSUE TITLE
Use the "placeholder" attribute on the "input" tag 

### ISSUE THREAD

**Issue by nixta** [Esri/esri.github.io#84]
There are a few nasty UI conflicts because the greyed out "Search by topic..." `placeholder` behavior is implemented by controlling the input field's `value` attribute.

To reproduce:
1. Enter some text (e.g. `runtime`).
2. Select a topic bubble (e.g. `runtime`).
2. Dismiss the topic bubble.
3. Start typing again.

2 issues seen. In both the following screenshots, I typed `runtime` again once the topic bubble had been dismissed.

1) The text is just appended to the placeholder.

![unknown](https://cloud.githubusercontent.com/assets/25374/24975286/1eb33472-1f93-11e7-9356-4f75a7cf04f4.png)

2) The placeholder disappears, but so does the start of the next text you type. Here it got as far as showing `Search by topic...ru` before the text was cleared, leaving only the `ntime` of `runtime`.

![unknown-1](https://cloud.githubusercontent.com/assets/25374/24975303/27aa090c-1f93-11e7-8780-7f8b2d0fe551.png)

The `input` tag used for search should be showing `Search by topic...` as a `placeholder` attribute, not the `value` attribute.

**Comment by jf990** [comment]
@nixta i was not able to tag you as a reviewer, can you test my branch and see if I addressed this? the UI is a bit different now but it seems to be something more intuitive.

**Comment by nixta** [comment]
Yeah, works much better. Nice work.

I think we should fix up the CSS before we release though. Seems the CSS from the old chosen library was just copied wholesale into our home.css and there isn't a proper match now. Should mostly be some overrides for the bubble sizes and backgrounds, and the chooser line height.

@alaframboise might have some insight here, but it was so long ago I wouldn't be surprised if that information has been flushed.

Cheers,

Nick.

**Comment by nixta** [comment]
Hmmm. I must be a foreigner in this repo. I can't assign myself, but I'll take a stab at updating the CSS.

**Comment by jgravois** [comment]
>I must be a foreigner in this repo.

not anymore. you've earned the :key:s

**Comment by nixta** [comment]
PR #99 submitted.
