### ISSUE TITLE
input tag spellcheck="false" attribute for mac OS

### ISSUE THREAD

**Issue by nixta** [Esri/esri.github.io#88]
Because Apple insist they know better than you what you meant to type, their spell-check auto-replace gets really aggressive.

![unknown-4](https://cloud.githubusercontent.com/assets/25374/24976046/f07272be-1f95-11e7-95ac-6feff4c57120.png)

By adding the `spellcheck="false"` attribute to a web form, we can avoid this. See [here](http://stackoverflow.com/questions/35513968/disable-auto-correct-in-safari-text-input).

**Comment by jf990** [comment]
i tested the new version on Safari, seems to work. but the inner workings of this thing it actually hides the real input control and replaces it with its own at runtime, so I wasn't sure if this setting was taking effect on the actual thing the user is typing in.

**Comment by nixta** [comment]
Yeah, the `spellcheck="false"` didn't make it through chosen-js's black box. Will research to see if there's a supported way to do this.
