### ISSUE TITLE
D language probably not actually right to include in search options

### ISSUE THREAD

**Issue by nixta** [Esri/esri.github.io#89]
There are two repos written in Objective-C that GitHub seems to believe are written in "D".

https://github.com/Esri/driving-directions-ios
and
https://github.com/Esri/offline-and-routing-data-collection-ios

Should see if we can correct this, and remove from the dropdown config.

**Comment by nixta** [comment]
Have pinged @alpascual to see what he knows about this.

**Comment by jgravois** [comment]
i've removed `d`. let me know if you need help going down the other rabbit hole.

**Comment by nixta** [comment]
@alpascual simple removed those other two repos. They were old and didn't serve any purpose.
