### ISSUE TITLE
add more user case study copy (e.g. "Smithsonian" or "U.S. Census Bureau").

### ISSUE THREAD

**Issue by nixta** [Esri/esri.github.io#94]
Each promoted topic has a cool looking project (although I'm not sure what the Gibbs Seed Company picture is showing), but I can't click on any of them to find out more.

Can we add links to each of them an discuss how they're using repos at github.com/esri?

**Comment by jf990** [comment]
didn't realize there was no link for these project

**Comment by jgravois** [comment]
for now we're just linking to the associated esri open source project, but lets leave this issue open for the time being and think more about expanding the explanation of the case study or linking out to the customer's own implementation instead.

**Comment by nixta** [comment]
I don't see a link, unless you mean the repos below. There's a headline, image, and description that aren't links.

If you do mean the repos below, it's sorta unclear to me what the connection is.

**Comment by jf990** [comment]
I just added a new link, on the img and the heading. But as John notes, the links on some of these projects may not necessarily be what we want because as we have them they don't go to the actual project, they go to the Esri tech that was used to build the project.

**Comment by jf990** [comment]
links are working
